#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
///*--------------------------------------------------------------------------------------------------------*\
//|*                                                                                                        *|
//|*                                   - Joypad Tetrix Simple Drive -                                       *|
//|*                                          ROBOTC on Tetrix                                              *|
//|*                                                                                                        *|
//|*  This program allows you to drive a robot via remote control using the extened joypad driver.          *|
//|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
//|*                                                                                                        *|
//|*                                        ROBOT CONFIGURATION                                             *|
//|*    NOTES:                                                                                              *|
//|*                                                                                                        *|
//|*    MOTORS & SENSORS:                                                                                   *|
//|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
//|*    Port D                  motorRight          12V                 Right motor                         *|
//|*    Port E                  motorLeft           12V                 Left motor                          *|
//\*---------------------------------------------------------------------------------------------------4246-*/
//

#include "Joypad.c"

task main(){

    //Setup joypad class
    Joypad joy1;

    //Initualize joypad, note the '&' when calling functions
    joypad_init(&joy1);

    while(true){
        //Update joystick values so that they can be used
        update(&joy1);
        
        motor[motorRight] = joy1.joy1_y;
        motor[motorLeft]  = joy1.joy2_y;
    }
}
