#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
///*--------------------------------------------------------------------------------------------------------*\
//|*                                                                                                        *|
//|*                                   - Joypad Tetrix Scaled Drive -                                       *|
//|*                                          ROBOTC on Tetrix                                              *|
//|*                                                                                                        *|
//|*  This program allows you to drive a robot via remote control using the extened joypad driver.          *|
//|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
//|*  This also has the added functionality where the Joysticks can be scaled for better control            *|
//|*                                                                                                        *|
//|*                                        ROBOT CONFIGURATION                                             *|
//|*    NOTES:                                                                                              *|
//|*                                                                                                        *|
//|*    MOTORS & SENSORS:                                                                                   *|
//|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
//|*    Port D                  motorRight          12V                 Right motor                         *|
//|*    Port E                  motorLeft           12V                 Left motor                          *|
//\*---------------------------------------------------------------------------------------------------4246-*/
//

#include "Joypad.c"

task main(){

    //Setup joypad class
    Joypad joy1;

    //Initualize joypad, note the '&' when calling functions
    joypad_init(&joy1);

    while(true){
        //Update joystick values so that they can be used
        update(&joy1);
        
        motor[motorRight] = joy1.joy1_y;
        motor[motorLeft]  = joy1.joy2_y;

        //If Button 'A' is pressed, set the joysticks to '100%' for faster movement
        if(isButtonPressed(&joy1, BUTTON_A){
           setJoystickScale(&joy1, 100);
        }

        //If Button 'B' is pressed, set the joysticks to '75%' for better control
        if(isButtonPressed(&joy1, BUTTON_B){
            setJoystickScale(&joy1, 75);
        }

        //IF button 'C' is pressod, set the joysticks to '50%' for the slowest control
        if(isButtonPressed(&joy1, BUTTON_C){
            setJoystickScale(&joy1, 50);
        }

        /*****************
         * Note: with this code, if 'A', 'B' and 'C' are pressed at the same time, the speed is set to 50
         *       Can you figure out why?
         *****************
    }
}
